[package]
name = "gps_webtransport_server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
rand = "0.9.1"
tracing = "0.1"
tracing-subscriber = "0.3"
tokio-tungstenite = "0.26.2"
tungstenite = "0.26.2"
futures-util = "0.3"